name: Docker Compose Actions

on:
  push:
    branches:
      - 'main'

jobs:
  docker-compose:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u nishitbaria --password-stdin

      - name: Run Docker Compose
        run: docker-compose -f compose.yaml up --build -d

      - name: Push to Docker Hub
        run: docker-compose -f docker/compose.yaml push
