name: Docker Compose Actions

on:
  push:
    branches:
      - 'main'

jobs:
  docker-compose:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        env:
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u nishitbaria --password-stdin

      - name: Set up Docker Compose
        run: |
          docker-compose -f compose.yml up --build -d

      - name: Tag Docker Image
        run: |
          IMAGE_NAME=nishitbaria/opengrame
          IMAGE_TAG=latest
          docker tag ${IMAGE_NAME}:${IMAGE_TAG} ${IMAGE_NAME}:${GITHUB_SHA}

      - name: Push Docker Image
        run: |
          IMAGE_NAME=nishitbaria/opengrame
          IMAGE_TAG=latest
          docker push ${IMAGE_NAME}:${IMAGE_TAG}
          docker push ${IMAGE_NAME}:${GITHUB_SHA}
